### ISSUE TITLE
Visualization: Automatically detect packages with DSD

### ISSUE THREAD

**Issue by timonegk** [bit-bots/dynamic_stack_decider#102]
# Summary
The DSD visualization should automatically detect the packages which use a DSD and show them in the GUI instead of relying on a hard-coded configuration file. 

## Is your feature request related to a problem?
The configuration file must be updated whenever other packages are restructured and cannot be shipped independently of these packages. 

## Describe the solution you'd like
There could be a marker in the package.xml file or a config file with the files could be added at a certain location. I think there are other pieces of software with ROS that work in such a way. Maybe the MoveIt plugin framework?

**Comment by Flova** [comment]
I would prefer a slightly different approach, where each dsd opens a service or latched topic, which returns a representation of the parsed tree. You could list all running DSD by listing all nodes with a service of that type. Additionally one would the client with the dsd qui wouldn't need to have the same version of the actions and decisions locally. This is relevant when we work with the robot and you e.g. only did a robot compile, so your local packages are out of sync. I worked on this in the past, but never finished it.
