### ISSUE TITLE
vis bug

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/dynamic_stack_decider#20]
![rqt_bug](https://user-images.githubusercontent.com/11520148/68382718-93fe0400-0154-11ea-8582-61e3e2b8b51f.png)
there is a wild timestamp or something similar on the right side at the JustUnpenalized decision.
Looks very strange to me.

**Comment by lilioid** [comment]
This is cause by the incorrect publishing of said debug data in the [JustUnpenalized decision](https://github.com/bit-bots/bitbots_behavior/blob/2de8ff9d43ae882eabb82e7ef1a45875f368170b/bitbots_body_behavior/src/bitbots_body_behavior/decisions/just_unpenalized.py#L7).
