### ISSUE TITLE
Use more non-binary decisions

### ISSUE THREAD

**Issue by lilioid** [bit-bots/dynamic_stack_decider#9]
Currently we have a lot of binary decisions in our dsd-tree which makes it unnecessarily large and overly complex.
For example we have a "BallClose" and another "BallDangerous" decision which either return "YES" or "NO". Instead we should implement more decisions like "BallDistance" which returns "FAR", "CLOSE", "DANGEROUS".

**Comment by NFiedler** [comment]
But your example is not a binary decision. BallDangerous is dependent on how close the ball is to the own goal (using self-localization), while BallClose decides whether the ball can be reached quickly by a player. Meaning, that all four true-false-combinations of these decisions are possible.
